INSERT INTO department (did, dname, fund) VALUES (1, 'HR', 500000);
INSERT INTO department (did, dname, fund) VALUES (2, 'IT', 1200000);
INSERT INTO department (did, dname, fund) VALUES (3, 'Finance', 800000);


INSERT INTO employee (eid, ename, dob, deptid) VALUES (101, 'Asha', '1995-04-12', 1);
INSERT INTO employee (eid, ename, dob, deptid) VALUES (102, 'Rahul', '1993-08-20', 2);
INSERT INTO employee (eid, ename, dob, deptid) VALUES (103, 'Meena', '1990-01-05', 3);



INSERT INTO dependent (empid, dependentname, age) VALUES (101, 'Anu', 5);
INSERT INTO dependent (empid, dependentname, age) VALUES (101, 'Kiran', 8);
INSERT INTO dependent (empid, dependentname, age) VALUES (102, 'Lakshmi', 30);


